FROM node:lts-alpine as build-stage

# development/production
ENV NODE_ENV=production

WORKDIR /app
COPY app .

RUN yarn run build

FROM nginx:1.15.10-alpine as runtime-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]