FROM node:lts-alpine as build-stage

# development/production
ENV NODE_ENV=development

RUN apk update && \
    npm install -g npm && \
    npm install -g @vue/cli

WORKDIR /app
COPY app .
RUN yarn install
RUN yarn run build

FROM nginx:1.15.10-alpine as runtime-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]