version: '3'
services:
  vue-cli:
    build: vue
    image: shinyay/vue-cli
    container_name: vue-cli
    ports:
      - 8080:8080
    volumes:
      - ./vue/app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
